- name: configure local host for AppCeneter developement work
  hosts: 127.0.0.1
  connection: local
  become: true
  tasks: 

    - name: Add Microsoft GPG key
      apt:
        state: present
        deb: https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb

    - name: Add Microsoft package key
      apt_key: 
        url: https://packages.microsoft.com/keys/microsoft.asc
        keyring: /etc/apt/trusted.gpg.d/microsoft.gpg

    - name: Add docker package key
      apt_key: 
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: Add Microsoft package repository 
      apt_repository:
        repo: "{{ item }}"
      loop: 
        -  "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable"
        -  "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ansible_distribution_release}} main"
    
    - name: Add VScode package respository
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
        state: present



    - name: Enable Universe package respository 
      apt_repository:
        repo: "{{ item }}"
      loop:
        - "deb http://archive.ubuntu.com/ubuntu/ bionic universe"
        - "deb http://archive.ubuntu.com/ubuntu/ bionic-updates universe"
        - "deb http://security.ubuntu.com/ubuntu/ bionic-security universe"

    - name: Update Apt cache
      apt: 
        update_cache: yes

    - name: Add all the packages.
      apt: 
        name: "{{ packages }}"
      vars:
        packages:
          - apt-transport-https
          - curl
          - ca-certificates
          - software-properties-common
          - docker-compose
          - powershell
          - azure-cli
          - git
          - terminator
          - dotnet-sdk-2.2
          - docker-ce


    - name: adding current user to group docker
      user:
        name={{ lookup('env', "USER") }}
        groups=docker
        append=yes

    - name: Install kubectl 
      command: snap install kubectl --classic
      args:
        creates: /snap/bin/kubectl

    - name: Create AppCenter secrets folder  
      file:
        path: ~/.acdev/secrets
        state: directory
        mode: 0644
    
    - name: Add VScode Liveshare Extention Pack
      become: false
      command: code --install-extension ms-vsliveshare.vsliveshare-pack
      ags:
        creates: ~/.vscode/extensions/ms-vsliveshare.vsliveshare-pack-0.2.10/package.json

    - name: Add VScode Extention C# 
      become: false
      command: code --install-extension ms-vscode.csharp 
      ags:
        creates: ~/.vscode/extensions/ms-vscode.csharp-1.18.0/package.json

    - name: Add VScode Extention Editorconfig
      become: false
      command: code --install-extension editorconfig.editorconfig
      ags:
        creates: ~/.vscode/extensions/editorconfig.editorconfig-0.13.0/package.json
    
    - name: Add VScode Extention DotNet Test Explorer
      become: false
      command: code --install-extension formulahendry.dotnet-test-explorer
      ags:
        creates: ~/.vscode/extensions/formulahendry.dotnet-test-explorer-0.6.5/package.json        

    - name: Add VScode Extention Docker
      become: false 
      command: code --install-extension peterjausovec.vscode-docker
      ags:
        creates: ~/.vscode/extensions/peterjausovec.vscode-docker-0.6.1/package.json        

    - name: Add VScode Extention LiveShare
      become: false 
      command: code --install-extension ms-vsliveshare.vsliveshare
      ags:
        creates: ~/.vscode/extensions/ms-vsliveshare.vsliveshare-0.3.1403/package.json      

    - name: Add VScode Extention Kubernetes Tools
      become: false 
      command: code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
      ags:
        creates: ~/.vscode/extensions/ms-kubernetes-tools.vscode-kubernetes-tools-0.1.18/package.json

    - name: Add VScode Extention YAML
      become: false 
      command: code --install-extension redhat.vscode-yaml
      ags:
        creates:  ~/.vscode/extensions/redhat.vscode-yaml-0.4.0/package.json        

    - name: Download and install MS cert microsoft-internal-ca.D17697.crt
      get_url:
        url: https://avalanchebuildsupport.blob.core.windows.net/files/microsoft-internal-ca.D17697.crt
        dest: ~/.acdev/tools/trusted-certs/microsoft-internal-ca.D17697.crt
        mode: 0644

    - name: Download and install MS cert msit-ca-z2.37AB15.crt
      get_url:
        url: https://avalanchebuildsupport.blob.core.windows.net/files/msit-ca-z2.37AB15.crt
        dest: ~/.acdev/tools/trusted-certs/msit-ca-z2.37AB15.crt
        mode: 0644

    - name: Download and install MS cert msit-ca-z2.377667.crt
      get_url:
        url: https://avalanchebuildsupport.blob.core.windows.net/files/msit-ca-z2.377667.crt
        dest: ~/.acdev/tools/trusted-certs/msit-ca-z2.377667.crt
        mode: 0644

    - name: Extract and install DotNet-PFX cert
      unarchive:
        src: https://avalanchebuildsupport.blob.core.windows.net/files/dotnet-pfxcert.zip
        dest: ~/.acdev/tools/dotnet-pfxcert
        mode: 0644
  
